# Generated by Django 4.1 on 2024-09-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0002_productlevelcashflow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductLevelCashflow',
            new_name='product_level_cashflows',
        ),
    ]
