# Generated by Django 4.1 on 2024-09-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0003_rename_productlevelcashflow_product_level_cashflows'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_level_cashflows',
            name='n_cash_flow_bucket',
            field=models.IntegerField(default=1188),
            preserve_default=False,
        ),
    ]
