# Generated by Django 4.1 on 2024-09-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0004_product_level_cashflows_n_cash_flow_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_level_cashflows',
            name='v_account_number',
            field=models.CharField(default=1188, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
