# Generated by Django 4.1 on 2024-09-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0005_product_level_cashflows_v_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_level_cashflows',
            name='v_account_number',
            field=models.CharField(max_length=255),
        ),
    ]
