# Generated by Django 4.1 on 2024-09-19 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0007_timebuckets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebuckets',
            name='multiplier',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timebuckets',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
