# Generated by Django 4.1 on 2024-09-20 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0008_alter_timebuckets_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBucketDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='timebuckets',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='timebuckets',
            name='definition',
            field=models.ForeignKey(default=1188, on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='ALM_APP.timebucketdefinition'),
            preserve_default=False,
        ),
    ]
