# Generated by Django 4.1 on 2024-09-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0015_aggregated_prod_cashflow_base_cashflow_by_bucket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityGapResultsBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('process_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('v_prod_code', models.CharField(max_length=50)),
                ('v_ccy_code', models.CharField(max_length=10)),
                ('bucket_start_date', models.DateField()),
                ('bucket_end_date', models.DateField()),
                ('inflows', models.DecimalField(decimal_places=2, max_digits=20)),
                ('outflows', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_liquidity_gap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cumulative_gap', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'liquidity_gap_results_base',
            },
        ),
    ]
