# Generated by Django 4.1 on 2024-10-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0018_alter_aggregatedcashflowbybuckets_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aggregatedcashflowbybuckets',
            table='ALM_APP_Aggregated_Acc_Cashflow',
        ),
    ]
