# Generated by Django 4.1 on 2024-10-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0019_alter_aggregatedcashflowbybuckets_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralPatternConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_prod_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BehavioralPatternEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenor', models.IntegerField()),
                ('multiplier', models.CharField(choices=[('Days', 'Days'), ('Months', 'Months'), ('Years', 'Years')], max_length=10)),
                ('percentage', models.FloatField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ALM_APP.behavioralpatternconfig')),
            ],
        ),
    ]
