# Generated by Django 4.1 on 2024-10-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0021_alter_behavioralpatternentry_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavioralpatternconfig',
            name='v_prod_type',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
