# Generated by Django 4.1 on 2024-10-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0025_behavioralpatternconfig_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralpatternentry',
            name='order',
            field=models.IntegerField(default=1188),
            preserve_default=False,
        ),
    ]
