# Generated by Django 4.1 on 2024-10-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0026_behavioralpatternentry_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralpatternconfig',
            name='created_by',
            field=models.CharField(default='System', max_length=100),
        ),
        migrations.AddField(
            model_name='behavioralpatternconfig',
            name='last_changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='behavioralpatternconfig',
            name='last_changed_by',
            field=models.CharField(default='System', max_length=100),
        ),
    ]
