# Generated by Django 4.1 on 2024-10-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0029_productfilter_process_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='reated_by',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='execution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
