# Generated by Django 4.1 on 2024-10-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0030_rename_reated_by_process_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_level_cashflows',
            name='record_count',
            field=models.IntegerField(default=0),
        ),
    ]
