# Generated by Django 4.1 on 2024-10-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0033_aggregated_prod_cashflow_base_v_loan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsi_expected_cashflow',
            name='management_fee_added',
            field=models.DecimalField(decimal_places=2, default=1188, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fsi_expected_cashflow',
            name='n_accrued_interest',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='fsi_expected_cashflow',
            name='n_exposure_at_default',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='fsi_expected_cashflow',
            name='v_loan_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fsi_expected_cashflow',
            unique_together={('fic_mis_date', 'v_account_number', 'd_cash_flow_date')},
        ),
    ]
