# Generated by Django 4.1 on 2024-10-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0034_fsi_expected_cashflow_management_fee_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_level_cashflows',
            name='V_CASH_FLOW_TYPE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
