# Generated by Django 4.1 on 2024-10-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0036_dim_product_v_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldn_product_master',
            name='v_prod_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
