# Generated by Django 4.1 on 2024-11-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0037_alter_ldn_product_master_v_prod_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dim_product',
            name='v_flow_type',
            field=models.CharField(blank=True, choices=[('Inflow', 'Inflow'), ('Outflow', 'Outflow')], max_length=10, null=True),
        ),
    ]
