# Generated by Django 4.1 on 2024-11-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0038_dim_product_v_flow_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquiditygapresultsbase',
            old_name='product_name',
            new_name='v_prod_type',
        ),
        migrations.AddField(
            model_name='liquiditygapresultsbase',
            name='n_total_cash_flow_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='liquiditygapresultsbase',
            name='n_total_interest_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='liquiditygapresultsbase',
            name='n_total_principal_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='liquiditygapresultsbase',
            name='v_loan_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liquiditygapresultsbase',
            name='v_prod_type_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='liquiditygapresultsbase',
            name='v_product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
