# Generated by Django 4.1 on 2024-11-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0041_alter_aggregated_prod_cashflow_base_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dim_product',
            name='v_balance_sheet_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dim_product',
            name='v_flow_type',
            field=models.CharField(blank=True, choices=[('Inflow', 'Inflow'), ('Outflow', 'Outflow')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dim_product',
            name='v_prod_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dim_product',
            name='v_prod_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
