# Generated by Django 4.1 on 2024-11-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0042_alter_dim_product_v_balance_sheet_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dim_dates',
            old_name='d_end_date',
            new_name='bucket_end_date',
        ),
        migrations.RenameField(
            model_name='dim_dates',
            old_name='d_start_date',
            new_name='bucket_start_date',
        ),
        migrations.AddField(
            model_name='dim_dates',
            name='bucket_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dim_dates',
            name='fic_mis_date',
            field=models.DateField(default='2024-11-15'),
            preserve_default=False,
        ),
    ]
