# Generated by Django 4.1 on 2024-11-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0043_rename_d_end_date_dim_dates_bucket_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dim_dates',
            name='d_calendar_date',
            field=models.DateField(null=True),
        ),
    ]
