# Generated by Django 4.1 on 2024-11-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0044_alter_dim_dates_d_calendar_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityGapResultsCons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('process_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=20)),
                ('v_prod_type', models.CharField(max_length=255)),
                ('v_prod_code', models.CharField(max_length=50)),
                ('v_ccy_code', models.CharField(max_length=10)),
                ('bucket_number', models.IntegerField()),
                ('bucket_start_date', models.DateField()),
                ('bucket_end_date', models.DateField()),
                ('inflows', models.DecimalField(decimal_places=2, max_digits=20)),
                ('outflows', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_liquidity_gap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cumulative_gap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('v_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('v_prod_type_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('v_loan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('n_total_cash_flow_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('n_total_principal_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('n_total_interest_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'liquidity_gap_results_cons',
            },
        ),
    ]
