# Generated by Django 5.1.3 on 2025-01-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0049_ldn_customer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldn_customer_info',
            name='v_party_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ldn_customer_info',
            name='v_party_type_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
