# Generated by Django 5.1.3 on 2025-01-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0052_alter_ldn_customer_info_v_party_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsi_expected_cashflow',
            name='v_cust_ref_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fsi_expected_cashflow',
            name='v_loan_type',
            field=models.CharField(max_length=50),
        ),
    ]
