# Generated by Django 5.1.3 on 2025-01-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0053_fsi_expected_cashflow_v_cust_ref_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_level_cashflows',
            name='v_party_type_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
