# Generated by Django 5.1.3 on 2025-01-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0054_product_level_cashflows_v_party_type_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregated_prod_cashflow_base',
            name='v_party_type_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
