# Generated by Django 5.1.3 on 2025-01-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0055_aggregated_prod_cashflow_base_v_party_type_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dim_product',
            name='v_product_splits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
