# Generated by Django 5.1.3 on 2025-01-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0056_dim_product_v_product_splits'),
    ]

    operations = [
        migrations.AddField(
            model_name='dim_product',
            name='v_party_type_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
