# Generated by Django 5.1.3 on 2025-01-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0057_dim_product_v_party_type_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_party_type_code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'party_type_mapping',
            },
        ),
    ]
