# Generated by Django 5.1.3 on 2025-01-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0061_processexecutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_rn',
            name='created_by',
            field=models.CharField(default='System', max_length=50),
        ),
        migrations.AddField(
            model_name='process_rn',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process_rn',
            name='execution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process_rn',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='processeRn', to='ALM_APP.productfilter'),
        ),
        migrations.AddField(
            model_name='process_rn',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='process_rn',
            name='modified_by',
            field=models.CharField(default='System', max_length=50),
        ),
        migrations.AddField(
            model_name='process_rn',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='process_rn',
            name='uses_behavioral_patterns',
            field=models.BooleanField(default=False),
        ),
    ]
