# Generated by Django 5.1.3 on 2025-01-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0062_process_rn_created_by_process_rn_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fsi_expected_cashflow',
            old_name='V_CASH_FLOW_TYPE',
            new_name='v_cash_flow_type',
        ),
        migrations.RenameField(
            model_name='fsi_expected_cashflow',
            old_name='V_CCY_CODE',
            new_name='v_ccy_code',
        ),
    ]
