# Generated by Django 5.1.3 on 2025-02-06 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0065_ldn_financial_instrument_n_curr_payment_recd'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Currency Code')),
                ('currency_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Currency Name')),
                ('reference_interest_rate_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference Interest Rate Code')),
                ('reporting_currency', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Reporting Currency')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=8, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'dim_currency',
            },
        ),
        migrations.CreateModel(
            name='DimExchangeRateConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate_api_key', models.CharField(max_length=255)),
                ('use_on_exchange_rates', models.BooleanField(default=False)),
                ('use_latest_exchange_rates', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dim_exchange_rate_conf',
            },
        ),
        migrations.CreateModel(
            name='LdnExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('v_from_ccy_code', models.CharField(max_length=3)),
                ('v_to_ccy_code', models.CharField(max_length=3)),
                ('n_exchange_rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('d_last_updated', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ldn_exchange_rate',
                'ordering': ['fic_mis_date'],
                'unique_together': {('fic_mis_date', 'v_from_ccy_code', 'v_to_ccy_code')},
            },
        ),
    ]
