# Generated by Django 5.1.3 on 2025-02-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0066_dimcurrency_dimexchangerateconf_ldnexchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimCurrencyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Currency Code')),
                ('name', models.CharField(max_length=255, verbose_name='Currency Name')),
            ],
            options={
                'verbose_name': 'Currency Master',
                'verbose_name_plural': 'Currencies Master',
                'db_table': 'dim_currency_master',
            },
        ),
    ]
