# Generated by Django 5.1.3 on 2025-02-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0067_dimcurrencymaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ldn_HQLA_Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_prod_code', models.CharField(max_length=20)),
                ('fic_mis_date', models.DateField()),
                ('v_prod_name', models.CharField(max_length=255, null=True)),
                ('v_prod_type', models.CharField(max_length=255, null=True)),
                ('v_prod_group_desc', models.CharField(max_length=255, null=True)),
                ('v_common_coa_code', models.CharField(max_length=20, null=True)),
                ('v_balance_sheet_category', models.CharField(max_length=20, null=True)),
                ('v_prod_type_desc', models.CharField(max_length=255, null=True)),
                ('v_load_type', models.CharField(max_length=20, null=True)),
                ('v_lob_code', models.CharField(max_length=20, null=True)),
                ('v_prod_desc', models.CharField(max_length=255, null=True)),
                ('v_hqla_level', models.CharField(max_length=10, null=True)),
                ('f_haircut_percentage', models.FloatField(null=True)),
                ('f_market_value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'LDN_HQLA_ASSET',
            },
        ),
    ]
