# Generated by Django 5.1.3 on 2025-02-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0068_ldn_hqla_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedLiquidityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('bucket_start_date', models.DateField()),
                ('bucket_end_date', models.DateField()),
                ('account_type', models.CharField(max_length=50)),
                ('v_prod_type', models.CharField(max_length=255)),
                ('v_prod_code', models.CharField(max_length=50)),
                ('v_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('v_product_splits', models.CharField(blank=True, max_length=255, null=True)),
                ('v_prod_type_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('v_ccy_code', models.CharField(max_length=10)),
                ('inflows', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('outflows', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('n_total_cash_flow_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('n_total_principal_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('n_total_interest_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'liquidity_data',
            },
        ),
    ]
