# Generated by Django 5.1.3 on 2025-02-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0069_extractedliquiditydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedliquiditydata',
            name='time_horizon_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
