# Generated by Django 5.1.3 on 2025-02-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0070_extractedliquiditydata_time_horizon_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedliquiditydata',
            name='process_name',
            field=models.CharField(default=-1212, max_length=100),
            preserve_default=False,
        ),
    ]
