# Generated by Django 5.1.3 on 2025-02-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0071_extractedliquiditydata_process_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LrmSelectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('selected_process_names', models.JSONField()),
                ('selected_product_types', models.JSONField()),
                ('selected_time_horizon', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lrm_selection_config',
            },
        ),
    ]
