# Generated by Django 5.1.3 on 2025-02-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0073_lrmtimehorizonconfig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lrmselectionconfig',
            name='fic_mis_date',
        ),
    ]
