# Generated by Django 5.1.3 on 2025-02-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0074_remove_lrmselectionconfig_fic_mis_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HQLAClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('v_prod_type', models.CharField(max_length=255, unique=True)),
                ('v_prod_code', models.CharField(max_length=50)),
                ('hqla_level', models.CharField(choices=[('Level 1', 'Level 1'), ('Level 2A', 'Level 2A'), ('Level 2B', 'Level 2B')], max_length=10)),
                ('ratings', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
            ],
            options={
                'db_table': 'hqla_classification',
            },
        ),
        migrations.CreateModel(
            name='HQLAStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('v_prod_type', models.CharField(max_length=255)),
                ('v_prod_code', models.CharField(max_length=50)),
                ('process_names', models.JSONField(default=list)),
                ('ratings', models.CharField(blank=True, max_length=50, null=True)),
                ('hqla_level', models.CharField(max_length=10)),
                ('n_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('v_ccy_code', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('weighted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('account_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hqla_stock',
            },
        ),
        migrations.AlterField(
            model_name='lrmselectionconfig',
            name='selection_purpose',
            field=models.CharField(choices=[('LCR', 'Liquidity Coverage Ratio'), ('NSFR', 'Net Stable Funding Ratio')], max_length=50, unique=True),
        ),
    ]
