# Generated by Django 5.1.3 on 2025-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0076_rename_process_names_hqlastock_v_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hqlaclassification',
            old_name='weight',
            new_name='risk_weight',
        ),
        migrations.RenameField(
            model_name='hqlastock',
            old_name='weight',
            new_name='risk_weight',
        ),
        migrations.AddField(
            model_name='hqlaclassification',
            name='haircut',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hqlaclassification',
            name='max_hqla_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hqlastock',
            name='adjusted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='hqlastock',
            name='max_hqla_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
