# Generated by Django 5.1.3 on 2025-02-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0077_rename_weight_hqlaclassification_risk_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hqlaclassification',
            name='v_prod_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hqlaclassification',
            name='v_prod_type',
            field=models.CharField(max_length=255),
        ),
    ]
