# Generated by Django 5.1.3 on 2025-02-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0078_alter_hqlaclassification_v_prod_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HQLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_2a_haircut', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('level_2b_haircut', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('level_2a_cap', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('level_2b_cap', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hqla_config',
            },
        ),
    ]
