# Generated by Django 5.1.3 on 2025-02-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0084_hqlastockoutflow_hqlaclassification_is_outflow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hqlaclassification',
            name='hqla_level',
            field=models.CharField(choices=[('Level 1', 'Level 1'), ('Level 2A', 'Level 2A'), ('Level 2B', 'Level 2B')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hqlastockoutflow',
            name='hqla_level',
            field=models.CharField(max_length=100),
        ),
    ]
