# Generated by Django 5.1.3 on 2025-02-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0085_alter_hqlaclassification_hqla_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HQLAStockInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('v_prod_type', models.CharField(max_length=255)),
                ('v_prod_code', models.CharField(max_length=50)),
                ('v_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ratings', models.CharField(blank=True, max_length=50, null=True)),
                ('hqla_level', models.CharField(max_length=100)),
                ('secondary_grouping', models.CharField(blank=True, max_length=100, null=True)),
                ('n_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('v_ccy_code', models.CharField(max_length=10)),
                ('risk_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('weighted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
            options={
                'db_table': 'hqla_stock_inflow',
            },
        ),
    ]
