# Generated by Django 5.1.3 on 2025-02-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0086_hqlastockinflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='hqlaclassification',
            name='is_inflow',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
