# Generated by Django 5.1.3 on 2025-02-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0087_hqlaclassification_is_inflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCRCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('v_prod_type', models.CharField(max_length=255)),
                ('v_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hqla_level', models.CharField(max_length=100)),
                ('n_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('v_ccy_code', models.CharField(max_length=10)),
                ('weighted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('net_cash_outflows', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('lcr_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'lcr_calculation',
            },
        ),
    ]
