# Generated by Django 5.1.3 on 2025-02-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0088_lcrcalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcrcalculation',
            name='category',
            field=models.CharField(default=-1212, max_length=50),
            preserve_default=False,
        ),
    ]
