# Generated by Django 5.1.3 on 2025-02-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0089_lcrcalculation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hqlastock',
            name='is_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hqlastock',
            name='total_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hqlastockinflow',
            name='is_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hqlastockinflow',
            name='total_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hqlastockoutflow',
            name='is_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hqlastockoutflow',
            name='total_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
