# Generated by Django 5.1.3 on 2025-02-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0090_hqlastock_is_total_hqlastock_total_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hqlastock',
            name='hqla_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hqlastock',
            name='n_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='hqlastock',
            name='risk_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
