# Generated by Django 5.1.3 on 2025-02-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0091_alter_hqlastock_hqla_level_alter_hqlastock_n_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcrcalculation',
            name='total_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
