# Generated by Django 5.1.3 on 2025-02-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0093_extractednsfrdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='extractednsfrdata',
            table='nsfr_data',
        ),
    ]
