# Generated by Django 5.1.3 on 2025-02-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0095_alter_extractednsfrdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSFRClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('v_nsfr_type', models.CharField(max_length=255)),
                ('v_prod_type_level', models.CharField(max_length=255)),
                ('v_prod_type', models.CharField(max_length=255)),
                ('factor_less_6_months', models.DecimalField(decimal_places=2, default=0.0, help_text='ASF/RSF factor for < 6 months horizon (%)', max_digits=5)),
                ('factor_6_to_12_months', models.DecimalField(decimal_places=2, default=0.0, help_text='ASF/RSF factor for ≥6 months to <1 year (%)', max_digits=5)),
                ('factor_greater_1_year', models.DecimalField(decimal_places=2, default=0.0, help_text='ASF/RSF factor for ≥1 year (%)', max_digits=5)),
            ],
            options={
                'db_table': 'nsfr_classification',
            },
        ),
    ]
