# Generated by Django 5.1.3 on 2025-02-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0097_nsfrstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nsfrclassification',
            old_name='factor_6_to_12_months',
            new_name='funding_factor_6_to_12_months',
        ),
        migrations.RenameField(
            model_name='nsfrclassification',
            old_name='factor_greater_1_year',
            new_name='funding_factor_greater_1_year',
        ),
        migrations.RenameField(
            model_name='nsfrclassification',
            old_name='factor_less_6_months',
            new_name='funding_factor_less_6_months',
        ),
    ]
