# Generated by Django 5.1.3 on 2025-02-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0098_rename_factor_6_to_12_months_nsfrclassification_funding_factor_6_to_12_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsfrstock',
            name='row_category',
            field=models.CharField(default='normal', help_text="Row type: 'normal', 'level_total', or 'overall_total'", max_length=50),
        ),
    ]
