# Generated by Django 5.1.3 on 2025-02-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0099_nsfrstock_row_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsfrstock',
            name='v_ccy_code',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
