# Generated by Django 5.1.3 on 2025-02-27 12:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0100_nsfrstock_v_ccy_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSFRStockSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('v_nsfr_type', models.CharField(max_length=255)),
                ('v_prod_type_level', models.CharField(max_length=255)),
                ('v_ccy_code', models.CharField(default='USD', max_length=10)),
                ('n_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of the three amount fields from NSFRStock (level_total rows)', max_digits=20)),
                ('total_calculated_sf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of the calculated stable funding amounts', max_digits=20)),
                ('row_category', models.CharField(default='normal', help_text="Row type: 'normal', 'level_total', or 'overall_total'", max_length=50)),
            ],
            options={
                'db_table': 'nsfr_stock_summary',
            },
        ),
    ]
