# Generated by Django 5.1.3 on 2025-02-27 13:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0101_nsfrstocksummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsfrstocksummary',
            name='nsfr_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final NSFR percentage calculated from overall AVAILABLE and REQUIRED stable funding', max_digits=10),
        ),
        migrations.AddField(
            model_name='nsfrstocksummary',
            name='total_available_sf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Calculated total (total_calculated_sf) for NSFRStock rows with v_nsfr_type = 'AVAILABLE STABLE FUNDING'", max_digits=20),
        ),
        migrations.AddField(
            model_name='nsfrstocksummary',
            name='total_required_sf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Calculated total (total_calculated_sf) for NSFRStock rows with v_nsfr_type = 'REQUIRED STABLE FUNDING'", max_digits=20),
        ),
        migrations.AlterField(
            model_name='nsfrstocksummary',
            name='row_category',
            field=models.CharField(default='normal', help_text="Row type: 'normal', 'level_total', 'overall_total', or 'summary'", max_length=50),
        ),
    ]
