# Generated by Django 5.1.3 on 2025-02-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0102_nsfrstocksummary_nsfr_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hqlaclassification',
            name='v_prod_type_level',
            field=models.CharField(default=-1212, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hqlastock',
            name='v_prod_type_level',
            field=models.CharField(default=-1212, max_length=255),
            preserve_default=False,
        ),
    ]
