# Generated by Django 5.1.3 on 2025-02-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALM_APP', '0104_remove_hqlaclassification_v_prod_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HQLAInflowOutflowClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('v_prod_type', models.CharField(max_length=255)),
                ('hqla_level', models.CharField(choices=[('Level 1', 'Level 1'), ('Level 2A', 'Level 2A'), ('Level 2B', 'Level 2B')], max_length=100)),
                ('v_prod_type_level', models.CharField(max_length=255)),
                ('secondary_grouping', models.CharField(blank=True, max_length=100, null=True)),
                ('ratings', models.CharField(blank=True, max_length=50, null=True)),
                ('risk_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('haircut', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_hqla_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('outflow_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_outflow', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('is_inflow', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
            ],
            options={
                'db_table': 'hqla_inflow_outflow_classification',
            },
        ),
    ]
