# Generated by Django 5.1.3 on 2025-01-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_audittrail'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='user_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='user_surname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
